# Currently written for cpu version

#FROM pytorch/pytorch:0.4.1-cuda9-cudnn7-runtime
#FROM ubuntu:16.04
FROM gcr.io/glit-server-fast/glit-server-fast:v2

RUN pip install Flask
RUN pip install gunicorn

COPY . /root

WORKDIR /root
USER root

#ENV LC_ALL=C.UTF-8
#ENV LANG=C.UTF-8

EXPOSE 8080
#CMD ["gunicorn", "server:app", "-b", ":8080", "--timeout", "1800"] # not for gae, works when removing entrypoint on yaml?
#ENTRYPOINT ["gunicorn"]
#CMD ["server:app"]
CMD ["python", "./server.py"] # currently works for gke, not for gae

#CMD ["uvicorn", "server_fastapi:app"]

