# Currently written for cpu version

FROM pytorch/pytorch:0.4.1-cuda9-cudnn7-runtime
#FROM ubuntu:16.04


COPY . /root

#RUN pip install pip -U && pip install -r requirements.txt
RUN pip install pip -U 

WORKDIR /root
USER root


RUN apt-get update
#RUN apt-get install sudo
#RUN apt-get install unzip
RUN apt install unzip
# Update to torch 1.1

RUN conda install pytorch-cpu==1.1.0 cpuonly -c pytorch
#RUN conda install pytorch-cpu==1.1.0 torchvision-cpu==0.3.0 cpuonly -c pytorch
#RUN conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=9.0 -c pytorch

RUN apt-get install g++

RUN pip install torch-scatter==1.1.2
RUN pip install torch-sparse==0.2.4
RUN pip install torch-cluster==1.2.4
#RUN pip install torch-spline-conv==1.1.0
RUN pip install torch-geometric==1.1.2
RUN conda install -c anaconda networkx==2.3
#RUN conda install -c rdkit rdkit
RUN conda install -c anaconda scipy==1.2
RUN conda install -c anaconda numpy==1.16

RUN pip install flask
RUN pip install fastapi pydantic uvicorn gunicorn
RUN pip install email-validator

